import Head from 'next/head'
import Header from '../Components/Header'
import Navbar from '../Components/Navbar'
import Results from '../Components/Results'
import requests from '../utils/requests'

export default function Home({results}) {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header  => step 1*/} 
        <Header />
      {/* Header  => step 1*/} 

      {/* Navigation  => step 2*/} 
        <Navbar />
      {/* Navigation  => step 2*/} 
      
      {/* Result  => step 3*/}
        <Results results={results}/>
      {/* Result  => step 3*/}

    </div>
  )
}

export const getServerSideProps = async (context) => {
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).then((res) => res.json())
  
  return{
    props: {
      results : request.results,
    }
  }
}
